<SplashScreenView>
    name: "splash_screen"
    MDFloatLayout:
        FitImage:
            source: "assets/images/abstract-luxury-gradient.png"
        MDCard:
            md_bg_color: 1, 1, 1, 1
            elevation: 4
            size_hint: .85, .9
            pos_hint: {"center_x": .5, "center_y": .5}
            radius: [10]

            Image:
                source: "assets/images/dhis2.png"
                # size_hint: 1, 1
                pos_hint: {"center_x": .5, "center_y": .6}
